services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myprivateproject
      MYSQL_USER: root
      MYSQL_PASSWORD: 20240901
    command:
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=1
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uapp -p$${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 10
  app:
    build: .
    container_name: mysql_container
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-XX:MaxRAMPercentage=75.0"
    ports:
      - "8080:8080"
volumes:
  dbdata: